# Site settings
title: Marek5050's Blog and Portfolio
email: marek.bejda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little bit of everything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marek5050.github.io" # the base hostname & protocol for your site
twitter_username: marek5050
github_username:  marek5050

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge
collections:
 - my_resume
plugins:
  - jekyll-seo-tag

twitter:
  username: marek5050

social:
  name: Marek Bejda
  links:
   - https://linked.com/in/marek5050
   - https://github.com/marek5050
   - https://twitter.com/marek5050