# Site settings
title: Marek5050's Blog and Portfolio
email: marek.bejda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little bit about everything, a jack of all trades, a master of none. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marek5050.github.io" # the base hostname & protocol for your site
twitter_username: marek5050
github_username:  marek5050

# Build settings
# markdown: kramdown
# highlighter: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
collections:
 - my_resume
