language: python
python:
   - "3.4"
sudo: false
addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - python-numpy

before_script:
    - uname -a
    - set
    - pip -V
    - pip freeze
    - python -V
    - coverage3 help | grep version
    - python -c "import numpy; print(numpy.__version__)"

script:
    - make collatz-tests
    - make Collatz.html
    - make Collatz.log
    - make test
    - make check
#    - make push
